apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ebp4t7c5p-nodejs
  janus-idp.io/tekton: ebp4t7c5p-nodejs
  backstage.io/kubernetes-id: ebp4t7c5p-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ebp4t7c5p-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
