apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ebp4t7c5p-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ebp4t7c5p-nodejs 
  name: ebp4t7c5p-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: ebp4t7c5p-nodejs 
