apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ebp4t7c5p-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-ea7b943ac5.xwcg.p3.openshiftapps.com/rhtap/rhtap-qe:073fb982edc6c7bd191c0d75c5026d34609c67c5@sha256:901b4e9bd27fceee83b22eab2536de30405d4f6903f415a5e952efdd37744757
          name: container-image
